shopping portal/sprint1_project/Shopping_portal1/Controllers/ShoppingController.cs
using Shopping_portal1.DAL;
using Shopping_portal1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Shopping_portal1.Controllers
{
    public class ShoppingController : Controller
    {
        // GET: Shopping
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult home_page()
        {
            return View();
        }

        public ActionResult login_controls(string select1)
        {
            string l_type = select1;

            if (l_type == "Admin_User")
            {
                return View("Admin_Login");
            }
            else if (l_type == "Cutomer_User")
            {
                return View("Customer_Login");
            }

            return View("home_page");
        }
        public ActionResult Customer_Login()
        {
            return View();
        }
        DalClass dl = new DalClass();
        public ActionResult prod1(string text1, string text2)
        {
            string uname = text1;
            string pwd = text2;

            bool flag = dl.Login_check(uname, pwd);

            if (flag == true)
            {
                return RedirectToAction("prd_page");
            }
            else
            {
                ViewBag.message1 = "Invalid Username/Password";
                return View("Customer_Login");
            }

            
        }
        public ActionResult Register()
        {
            return RedirectToAction("Create", "Users");
        }
        public ActionResult Admin_Login()
        {
            return View();
        }
        public ActionResult admin_pannel(string text1, string text2)
        {
            bool status = dl.validate_admin(text1, text2);
            if (status == true)
            {
                return RedirectToAction("Index", "Products");
            }
            else
            {
                ViewBag.message = "Invalid Credentials";
                return View("Admin_Login");
            }
        }
        public ActionResult prd_page()
        {
            List<Product> ls = dl.product_list();
            return View(ls);
        }
        public ActionResult prd_details(int prodid)
        {
            Product ob = dl.prodduct_details(prodid);
            return View(ob);
        }
    }
}

shopping portal/sprint1_project/Shopping_portal1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Shopping Portal</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <!--<div class="navbar navbar-inverse navbar-fixed-top">
        
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>-->
                @*@Html.ActionLink("Shopping Poratl", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            
            @*<div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Portal", "home_page","Shopping")</li>
                </ul>
            </div>*@
        <!--</div>-->
    @*</div>*@
    <div class=" body-content">
        @RenderBody()
        @*<footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>